repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        exclude: '.clang-format'

#  - repo: https://github.com/yoheimuta/protolint
#    rev: v0.35.2
#    hooks:
#      - id: protolint
